# Generated by Django 6.0.1 on 2026-01-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
